spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DATABASE}
        username: ${USERNAME}
        password: ${PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                default_batch_fetch_size: 100
server:
    port: 8080

jwt:
    secret: ${SECRETKEY}
    expiration: 36000000